/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        "bottom-panel-xs": "280px",
        "pane-xs": "360px",
        "form-narrow": "400px",
        "toolbar-narrow": "420px",
        "history-narrow": "480px",
        "panel-narrow": "520px",
        "surface-stacked": "780px",
        "changes-toolbar": "1100px",
      },
      fontFamily: {
        // Every family resolves through tokens.css; never var(--vscode-*).
        app: "var(--nx-font-app)",
        ui: "var(--nx-font-ui)",
        code: "var(--nx-font-code)",
        editor: "var(--nx-font-code)",
        sans: "var(--nx-font-ui)",
      },
      fontSize: {
        // Type scale. `text-ui*` are the GitView UI sizes, `text-code`/`editor`
        // follow the VS Code editor font setting.
        "ui-base": "var(--nx-font-size-base)",
        ui: "var(--nx-font-size-ui)",
        "ui-sm": "var(--nx-font-size-ui-sm)",
        section: "var(--nx-font-size-section)",
        title: "var(--nx-font-size-title)",
        micro: "var(--nx-font-size-micro)",
        code: "var(--nx-font-size-code)",
        editor: "var(--nx-font-size-code)",
        // Purpose-specific sizes for dense metadata and status chrome.
        "file-glyph": "var(--nx-font-size-file-glyph)",
        path: "var(--nx-font-size-path)",
        "editor-ui": "var(--nx-font-size-editor-ui)",
        status: "var(--nx-font-size-status)",
      },
      /*
       * Density + geometry scale. Components use these names instead of
       * literal pixel utilities so the whole UI retunes from tokens.css.
       */
      spacing: {
        // Vertical rhythm of the chrome; see tokens.css. `code` is the shared
        // code/diff line box and is listed here so `min-h-code` lines up with
        // `leading-code`.
        "icon-sm": "var(--nx-icon-sm)",
        "icon-md": "var(--nx-icon-md)",
        "icon-lg": "var(--nx-icon-lg)",
        row: "var(--nx-row-h)",
        control: "var(--nx-control-h)",
        toolbar: "var(--nx-toolbar-h)",
        "row-lg": "var(--nx-row-h-lg)",
        "log-graph-row": "var(--nx-log-graph-row-h)",
        "control-lg": "var(--nx-control-h-lg)",
        header: "var(--nx-header-h)",
        "menu-item": "var(--nx-menu-item-h)",
        code: "var(--nx-line-h-code)",
        "pad-x": "var(--nx-pad-x)",
        "pad-panel": "var(--nx-pad-panel)",
        "menu-pad-x": "var(--nx-menu-pad-x)",
        "menu-pad-y": "var(--nx-menu-pad-y)",
        "section-gap": "var(--nx-section-gap)",
        "tab-title": "var(--nx-width-tab-title)",
        "changes-files": "var(--nx-width-changes-files-pane)",
        "changes-files-min": "var(--nx-width-changes-files-min)",
        "changes-commit": "var(--nx-width-changes-commit-pane)",
        "changes-commit-min": "var(--nx-width-changes-commit-min)",
        "conflict-actions": "var(--nx-width-conflict-actions)",
        "branch-menu": "var(--nx-width-branch-menu)",
        "branch-compare": "var(--nx-width-branch-compare)",
        "blame-hover-min": "var(--nx-width-blame-hover-min)",
        "blame-hover-max": "var(--nx-width-blame-hover-max)",
        "blame-gutter-min": "var(--nx-width-blame-gutter-min)",
        "blame-gutter": "var(--nx-width-blame-gutter)",
        "log-menu": "var(--nx-width-log-menu)",
        "log-search": "var(--nx-width-log-search)",
        "filter-value": "var(--nx-width-filter-value)",
        "review-filter": "var(--nx-width-review-filter)",
        "temporary-prefix": "var(--nx-width-temporary-prefix)",
        "history-search": "var(--nx-width-history-search)",
        "search-field": "var(--nx-width-search-field)",
        "search-count": "var(--nx-width-search-count)",
        "changes-close": "var(--nx-width-changes-close)",
        "conflicts-close": "var(--nx-width-conflicts-close)",
        "diff-gutter": "var(--nx-width-diff-gutter)",
        "blame-column": "var(--nx-width-blame-column)",
        "commit-message": "var(--nx-height-commit-message)",
        "commit-scope-max": "var(--nx-height-commit-scope-max)",
        "commit-body-min": "var(--nx-height-commit-body-min)",
        "edit-message": "var(--nx-height-edit-message)",
        "diff-preview-header": "var(--nx-height-diff-preview-header)",
        "git-widget-header": "var(--nx-height-git-widget-header)",
        "tree-section": "var(--nx-height-tree-section)",
        "stash-list-max": "var(--nx-height-stash-list-max)",
        "sync-targets-max": "var(--nx-height-sync-targets-max)",
        "update-targets-max": "var(--nx-height-update-targets-max)",
        "log-details-max": "var(--nx-height-log-details-max)",
        "review-timeline-max": "var(--nx-height-review-timeline-max)",
        "review-description": "var(--nx-height-review-description)",
        "review-comment": "var(--nx-height-review-comment)",
        "review-comments-max": "var(--nx-height-review-comments-max)",
        splitter: "var(--nx-size-splitter)",
        "splitter-active": "var(--nx-size-splitter-active)",
        "blame-accent": "var(--nx-size-blame-accent)",
        "commit-field": "var(--nx-space-commit-field)",
        "control-gap": "var(--nx-space-control-gap)",
        "form-gap": "var(--nx-space-form-gap)",
        "action-gap": "var(--nx-space-action-gap)",
        "widget-gap": "var(--nx-space-widget-gap)",
        "footer-pad-y": "var(--nx-space-footer-pad-y)",
        "widget-control-x": "var(--nx-space-widget-control-x)",
        "badge-x": "var(--nx-space-badge-x)",
      },
      lineHeight: {
        row: "var(--nx-row-h)",
        "log-graph-row": "var(--nx-log-graph-row-h)",
        code: "var(--nx-line-h-code)",
        "commit-body": "var(--nx-line-height-commit-body)",
        ref: "var(--nx-line-height-ref)",
      },
      borderWidth: {
        "blame-accent": "var(--nx-size-blame-accent)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        ring: "var(--ring)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          hover: "var(--primary-hover)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          hover: "var(--secondary-hover)",
        },
        input: {
          DEFAULT: "var(--input)",
          foreground: "var(--input-foreground)",
          border: "var(--input-border)",
        },
        list: {
          hover: "var(--list-hover)",
          active: "var(--list-active)",
          activeForeground: "var(--list-active-foreground)",
        },
        menu: {
          bg: "var(--menu-bg)",
          fg: "var(--menu-fg)",
          border: "var(--menu-border)",
          selection: "var(--menu-selection)",
          selectionForeground: "var(--menu-selection-foreground)",
        },
        toolbar: {
          hover: "var(--toolbar-hover)",
        },
        // --- Theme adapter aliases -------------------------------------
        // Names kept from the pre-existing `vscode-*` utilities so the 200+
        // existing call sites keep working; each now points at a semantic
        // token instead of reading var(--vscode-*) directly.
        "vscode-description": "var(--nx-muted)",
        "vscode-link": "var(--nx-link)",
        "vscode-editor-bg": "var(--nx-bg)",
        "vscode-editor-fg": "var(--nx-editor-fg)",
        "vscode-line-number": "var(--nx-line-number)",
        "vscode-panel-border": "var(--nx-panel-border)",
        "vscode-widget-bg": "var(--nx-panel2)",
        "vscode-sidebar-bg": "var(--nx-chrome-bg)",
        "vscode-titlebar-bg": "var(--nx-titlebar-bg)",
        "vscode-error": "var(--nx-danger-fg)",
        // --- Text ------------------------------------------------------
        fg: "var(--nx-text)",
        "editor-fg": "var(--nx-editor-fg)",
        "icon-fg": "var(--nx-icon-fg)",
        "sidebar-title-fg": "var(--nx-sidebar-title-fg)",
        "hover-fg": "var(--nx-hover-fg)",
        "testing-passed": "var(--nx-testing-passed)",
        "charts-yellow": "var(--nx-charts-yellow)",
        // --- Validation / feedback --------------------------------------
        "danger-bg": "var(--danger-background)",
        "danger-fg": "var(--danger-foreground)",
        "danger-border": "var(--danger-border)",
        "warning-bg": "var(--nx-warning-bg)",
        "warning-fg": "var(--nx-warning-fg)",
        "warning-border": "var(--nx-warning-border)",
        "info-bg": "var(--nx-info-bg)",
        "info-fg": "var(--nx-info-fg)",
        "editor-warning-bg": "var(--nx-editor-warning-bg)",
        "editor-warning-fg": "var(--nx-editor-warning-fg)",
        "editor-warning-border": "var(--nx-editor-warning-border)",
        "editor-error-fg": "var(--nx-editor-error-fg)",
        "editor-info-bg": "var(--nx-editor-info-bg)",
        "editor-info-fg": "var(--nx-editor-info-fg)",
        "editor-info-border": "var(--nx-editor-info-border)",
        // --- Surfaces ----------------------------------------------------
        "panel-bg": "var(--nx-panel)",
        "sidebar-section-bg": "var(--nx-sidebar-section-bg)",
        "tabs-bg": "var(--nx-tabs-bg)",
        "gutter-bg": "var(--nx-gutter-bg)",
        "hover-bg": "var(--nx-hover-bg)",
        "code-block-bg": "var(--nx-code-block-bg)",
        "editor-inactive-sel": "var(--nx-editor-inactive-sel)",
        "list-inactive-sel": "var(--nx-list-inactive-sel)",
        "tab-active-bg": "var(--nx-tab-active-bg)",
        "tab-active-fg": "var(--nx-tab-active-fg)",
        "tab-inactive-fg": "var(--nx-tab-inactive-fg)",
        "badge-bg": "var(--nx-badge-bg)",
        "badge-fg": "var(--nx-badge-fg)",
        "menu-separator": "var(--nx-menu-separator)",
        "overview-ruler-bg": "var(--nx-overview-ruler-bg)",
        "overlay-modal": "var(--nx-overlay-modal)",
        "overlay-subtle": "var(--nx-overlay-subtle)",
        // --- Controls ----------------------------------------------------
        "button-border": "var(--nx-button-border)",
        "checkbox-bg": "var(--nx-checkbox-bg)",
        "checkbox-border": "var(--nx-checkbox-border)",
        "checkbox-fg": "var(--nx-checkbox-fg)",
        "control-placeholder": "var(--control-placeholder)",
        // --- Borders / elevation -----------------------------------------
        "group-border": "var(--nx-group-border)",
        "widget-border": "var(--nx-widget-border)",
        "widget-shadow": "var(--nx-widget-shadow)",
        // --- Foundational --nx-* aliases ---------------------------------
        faint: "var(--nx-faint)",
        "nx-border": "var(--nx-border)",
        "nx-red": "var(--nx-red)",
        "nx-orange": "var(--nx-orange)",
        "nx-blue": "var(--nx-blue)",
        "nx-green": "var(--nx-green)",
        "chrome-fg": "var(--nx-chrome-fg)",
        // --- File-type palette (brand colours, not theme colours) ----------
        lang: {
          ts: "var(--nx-lang-ts)",
          tsx: "var(--nx-lang-tsx)",
          js: "var(--nx-lang-js)",
          jsx: "var(--nx-lang-jsx)",
          "jsx-ink": "var(--nx-lang-jsx-ink)",
          json: "var(--nx-lang-json)",
          md: "var(--nx-lang-md)",
          css: "var(--nx-lang-css)",
          html: "var(--nx-lang-html)",
          py: "var(--nx-lang-py)",
          yaml: "var(--nx-lang-yaml)",
          image: "var(--nx-lang-image)",
          "on-dark": "var(--nx-lang-on-dark)",
          "on-light": "var(--nx-lang-on-light)",
        },
        // --- Git status ---------------------------------------------------
        status: {
          added: "var(--nx-status-added)",
          modified: "var(--nx-status-modified)",
          deleted: "var(--nx-status-deleted)",
          untracked: "var(--nx-status-untracked)",
          ignored: "var(--nx-status-ignored)",
          conflict: "var(--nx-status-conflict)",
          renamed: "var(--nx-status-renamed)",
        },
      },
      borderRadius: {
        vscode: "var(--nx-menu-radius)",
      },
      boxShadow: {
        popover: "var(--nx-shadow-popover)",
        modal: "var(--nx-shadow-modal)",
      },
      keyframes: {
        "blame-hover-fade": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "blame-pulse": {
          "0%, 100%": { opacity: "0.35" },
          "50%": { opacity: "0.65" },
        },
      },
      animation: {
        "blame-hover-fade": "blame-hover-fade 0.08s ease-out",
        "blame-pulse": "blame-pulse 1.4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
  // Disable Preflight to avoid conflicts with VS Code webview styles
  corePlugins: {
    preflight: false,
  },
};
