import { create } from "zustand";
import { createGitWorkspaceStoreSlice } from "./gitWorkspaceStoreSlice";
import { createRootLogFilters } from "./gitWorkspaceLogDefaults";
import type { GitWorkspaceActions, GitWorkspaceState } from "./gitWorkspaceStoreTypes";

export type { GitWorkspaceState } from "./gitWorkspaceStoreTypes";

export const useGitWorkspaceStore = create<GitWorkspaceState & GitWorkspaceActions>(
  (set, get) => ({
    loading: true,
    error: null,
    dialogs: {},
    nativeFocusSurface: null,
    repoSnapshot: null,
    repoEpoch: 0,
    statusSnapshot: null,
    syncOperations: [],
    branchSnapshot: null,
    branchCompareSnapshot: null,
    branchCompareOpen: false,
    branchCompareSelectedFile: null,
    diffDocument: null,
    diffLoading: false,
    diffError: null,
    selectedFilePath: null,
    commitScope: new Set(),
    commitMessage: "",
    amend: false,
    signoff: false,
    gpgSign: false,
    author: "",
    runChecks: true,
    runHooks: true,
    pullStrategy: "merge",
    synchronousBranchControl: true,
    branchesOpen: false,
    branchesLoading: false,
    workspaceTab: "log",
    temporarySubTab: "stash",
    stashSnapshot: null,
    shelfSnapshot: null,
    tagsOpen: false,
    tagsLoading: false,
    tagSnapshot: null,
    worktreesOpen: false,
    worktreesLoading: false,
    worktreeSnapshot: null,
    patchPreview: null,
    workspaceNotification: null,
    logSnapshot: null,
    logDag: null,
    logLoading: false,
    logLoadingMore: false,
    logError: null,
    logSelectedSha: null,
    logSelectedShas: [],
    logSelectedFilePath: null,
    logFilters: createRootLogFilters(),
    logRootRequest: 0,
    historyOpenRequest: null,
    activeHistoryScope: null,
    pendingRollback: null,
    issueTrackerBaseUrl: null,
    diffStagedView: false,
    diffViewMode: "side_by_side",
    whitespacePolicy: "doNotIgnore",
    commitAfterChecksConfirmed: false,
    reviewSnapshot: null,
    reviewDetails: null,
    reviewLoading: false,
    reviewError: null,
    reviewFilters: { state: "open", sort: "updated" },
    selectedReviewId: null,

    ...createGitWorkspaceStoreSlice(set, get),
  }),
);
